name: Quality

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          extensions: mbstring, pdo_mysql, pdo_sqlite

      - uses: ramsey/composer-install@v3

      - uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: npm

      - run: npm ci
      - run: npm run build
      - run: composer validate --strict --no-check-publish
      - run: vendor/bin/pint --test
      - run: vendor/bin/pest
